### ISSUE TITLE
curl "http://p.3.cn/prices/mgets?callback=jQuery1377247^&type=1^&area=1_72_4137_0^&skuIds=J_7437788^%^2CJ_100000177756^%^2CJ_5821455^&pdbp=0^&pdtk=^&pdpin=^&pduid=^&source=list_pc_front^&_=1542186498283" -H "Accept: */*" -H "Connection: keep-alive" -H "Accept-Encoding: gzip, deflate" -H "Referer: http://list.jd.com/list.html?cat=9987,653,655" -H "Accept-Language: zh-CN,zh;q=0.9" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" --compressed

### ISSUE THREAD

**Issue by Zhangfredy** [NickCarneiro/curlconverter#107]

**Comment by Zhangfredy** [comment]
Incorrect operation

**Comment by cf512** [comment]
I looked into this and the `Error parsing curl command` seems to be because of escaping characters in the p.3.cn URI. Console errors were logged as: `"URIError: URI malformed"`. 

When I removed the ^'s manually, it then converted successfully.

Updated Input:

`curl -H "Accept: */*" -H "Connection: keep-alive" -H "Accept-Encoding: gzip, deflate" -H "Referer: http://list.jd.com/list.html?cat=9987,653,655" -H "Accept-Language: zh-CN,zh;q=0.9" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" "http://p.3.cn/prices/mgets?callback=jQuery1377247&type=1&area=1_72_4137_0&skuIds=J_7437788%2CJ_100000177756%2CJ_5821455&pdbp=&pdtk=&pdpin=&pduid=&source=list_pc_front&_=1542186498283" --compressed`

Can you confirm if your original input was from Windows curl cmd?

**Comment by romadrutskii** [comment]
PR #233 fixed the issue.

**Comment by verhovsky** [comment]
Duplicate of #143
