### ISSUE TITLE
curl -d does not work for node

### ISSUE THREAD

**Issue by richwednesday** [NickCarneiro/curlconverter#109]
See sample curl command below to convert to node

`curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '18233982904' 'http://198.30.191.00:8309/CurlToNode'`

**Comment by ErwinLengkeek** [comment]
Seems to be related to the number-only body that is being passed. Appending or prepending it with a letter fixes the parsing. The console gives the error 'request.data.indexOf is not a function'.

**Comment by dendrochronology** [comment]
I had a similar problem with this trying to upload images to Filestack. Turns out I was missing the `"Content-Type": "application/x-www-form-urlencoded"` header.

    curl -X POST -d url="https://example.com/ponies.png" "https://www.filestackapi.com/api/store/S3?key=MY_API_KEY"

... converted to this:

    var dataString = 'url=https://example.com/ponies.png';

    var options = {
        url: 'https://www.filestackapi.com/api/store/S3?key=MY_API_KEY',
        method: 'POST',
        body: dataString
    };

But it really _should_ be this:

    var options = {
        url: 'https://www.filestackapi.com/api/store/S3?key=MY_API_KEY',
        method: 'POST',
        body: dataString
        headers: {
          "Content-Type": "application/x-www-form-urlencoded"
        },
    };

I haven't yet dug into the code to see how `curlconverter` decides on which encoding to use, but that fixed it for me.
