### ISSUE TITLE
Add fetch

### ISSUE THREAD

**Issue by jimmywarting** [NickCarneiro/curlconverter#69]
Using node-fetch instead of Request. it's also good cuz it can work in browser to.

**Comment by NickCarneiro** [comment]
It's unlikely I'll get around to this, but happy to look at a PR. I'll leave the ticket open for +1s.

**Comment by jimmywarting** [comment]
I was looking in to making a PR, but the code is super weird.
tried to make a copy of node.js

request.headers seems to be an array but are handeld like an object?
You know that a header can exist more once?

https://stackoverflow.com/questions/3241326/set-more-than-one-http-header-with-the-same-name

So I actually think it should be a 2D array...


---

Just wondering what are the lowest requirement for this package?
looks like some really old code style with lots of backward compatible. and not being able to use new es6 features

**Comment by NickCarneiro** [comment]
I've created #70 to handle the duplicate headers.

I wanted to keep the build process simple for the downstream project, curltorequests, but it's a lot easier to transpile es6 with babel since this project began.

Go ahead and target node 8 and we'll leave it up to downstream packages to manage their own builds to whatever version of js they want.

**Comment by verhovsky** [comment]
Support added in #242 (see the duplicate issue #241)
